name: Validate CloudFormation
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cfn-lint
        run: |
          pip install cfn-lint
          cfn-lint templates/**/*.yaml
