AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC básica com 2 subnets públicas e uma route table pública'
Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
Outputs:
  VpcId:
    Value: !Ref VPC
